name: Build Game Executables

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame pyinstaller
        pip install "setuptools<58"

    - name: Build executable with PyInstaller
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          pyinstaller --onefile --add-data "assets;assets" main.py
        else
          pyinstaller --onefile --add-data "assets:assets" main.py
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MazeGame-${{ matrix.os }}
        path: dist/